// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn("[Supabase] Missing environment variables. Returning mock client for preview bypass.");
    
    const mockPropertiesList = [
      {
        id: "d9747eee-6cc2-42b4-9749-b5173614cd54",
        category: "dubai-apartments",
        title: "Marina View Residences",
        location: "Dubai Marina",
        price: "AED 2.4M",
        bedrooms: "2 BR",
        area: "1,250 sqft",
        description: "Panoramic marina views with premium finishes and resort-style amenities.",
        full_description: "Enjoy luxurious living in the heart of Dubai Marina. This stunning 2-bedroom apartment offers breathtaking panoramic views of the water, a state-of-the-art kitchen with integrated appliances, and a spacious balcony perfect for entertaining. Residents gain exclusive access to a temperature-controlled infinity pool, modern gym, and 24/7 concierge services.",
        image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80",
        image_path: null,
        gallery: [
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80"
        ],
        highlights: ["Panoramic Marina Views", "Infinity Pool Access", "24/7 Concierge", "Integrated Kitchen Appliances"],
        featured: true,
        published: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "f57c7b3b-2ef8-48db-88c7-d8cf71b349be",
        category: "dubai-commercial",
        title: "Business Bay Tower Floor",
        location: "Business Bay",
        price: "AED 6.2M",
        bedrooms: null,
        area: "4,500 sqft",
        description: "Full-floor Grade-A office with skyline views and secure parking.",
        full_description: "A premium full-floor commercial space located in the bustling business district of Business Bay. Fully fitted with partitions, executive offices, meeting rooms, and open workstations. Offers panoramic canal and Burj Khalifa views, dedicated server room, private pantry, and 8 secure parking bays.",
        image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80",
        image_path: null,
        gallery: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80"],
        highlights: ["Burj Khalifa Views", "Grade-A Fitting", "8 Parking Spaces", "Canal Frontage"],
        featured: false,
        published: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "97bb159b-0de3-44b6-bbfb-21738772351b",
        category: "india-land",
        title: "Alibaug Sea-Facing Plot",
        location: "Alibaug, Maharashtra",
        price: "₹ 3.2 Cr",
        bedrooms: null,
        area: "12,000 sqft",
        description: "Titled sea-view plot ideal for a private villa or boutique retreat.",
        full_description: "A pristine 12,000 sqft sea-facing plot in Alibaug, the premium getaway destination. Clear title, demarcated boundary wall, and fully sanctioned for a luxurious second home. Boasts mature coconut groves and direct road access.",
        image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        image_path: null,
        gallery: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80"],
        highlights: ["Clear Sea Views", "Demarcated Boundary", "Second Home Sanctions", "Mature Coconut Groves"],
        featured: true,
        published: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }
    ];

    const mockCareersList = [
      {
        id: "c9747eee-6cc2-42b4-9749-b5173614cd54",
        title: "Real Estate Broker",
        department: "Sales",
        location: "Dubai Marina Office",
        type: "Full-time",
        description: "Looking for an experienced broker with a track record in luxury sales.",
        requirements: ["3+ years experience in Dubai", "Strong communication skills", "Proven sales record"],
        published: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }
    ];

    const createMockPostgrest = (tableName: string) => {
      let currentData = tableName === "properties" 
        ? [...mockPropertiesList] 
        : tableName === "careers" 
          ? [...mockCareersList] 
          : [];

      const builder: any = {
        select: () => builder,
        eq: (field: string, val: any) => {
          currentData = currentData.filter(item => (item as any)[field] === val);
          return builder;
        },
        neq: () => builder,
        gt: () => builder,
        lt: () => builder,
        order: () => builder,
        limit: () => builder,
        single: () => Promise.resolve({ data: currentData[0] || null, error: null }),
        maybeSingle: () => Promise.resolve({ data: currentData[0] || null, error: null }),
        insert: async (payload: any) => {
          return { data: payload, error: null };
        },
        then: (onfulfilled: any) => Promise.resolve({ data: currentData, error: null }).then(onfulfilled),
      };
      return builder;
    };

    return {
      auth: {
        getUser: async () => ({ data: { user: { id: "mock-user-id", email: "admin@example.com", user_metadata: {} } }, error: null }),
        getSession: async () => ({ data: { session: null }, error: null }),
        signInWithPassword: async () => ({ data: { user: { id: "mock-user-id", email: "admin@example.com" }, session: {} }, error: null }),
        signUp: async () => ({ data: { user: { id: "mock-user-id", email: "admin@example.com" }, session: {} }, error: null }),
        signOut: async () => ({ error: null }),
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      },
      from: (tableName: string) => createMockPostgrest(tableName),
      storage: {
        from: () => ({
          createSignedUrl: async (path: string) => ({ data: { signedUrl: path }, error: null }),
          upload: async () => ({ data: { path: "mock-path" }, error: null }),
          remove: async () => ({ error: null }),
        }),
      },
    } as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

